var cellInformation = {
  "Nuclear envelope": "The nuclear envelope (NE) is a highly regulated membrane barrier that separates the nucleus from the cytoplasm in eukaryotic cells. It contains a large number of different proteins that have been implicated in chromatin organization and gene regulation. Although the nuclear membrane enables complex levels of gene expression, it also poses a challenge when it comes to cell division. To allow access of the mitotic spindle to chromatin, the nucleus of metazoans must completely disassemble during mitosis, generating the need to re-establish the nuclear compartment at the end of each cell division.",

  "Nucleus": "The nucleus is a membrane-bound organelle that contains genetic material (DNA) of eukaryotic organisms. As such, it serves to maintain the integrity of the cell by facilitating transcription and replication processes. It's the largest organelle inside the cell taking up about a tenth of the entire cell volume. This makes it one of the easiest organelles to identify under the microscope.",

  "Plasma membrane": "The plasma membrane, also called the cell membrane, is the membrane found in all cells that separates the interior of the cell from the outside environment. In bacterial and plant cells, a cell wall is attached to the plasma membrane on its outside surface. The plasma membrane consists of a lipid bilayer that is semipermeable. The plasma membrane regulates the transport of materials entering and exiting the cell.",

  "Rough endoplasmic reticulum": "The rough endoplasmic reticulum is made up of membranes which have ribosomes attached to it. This gives it the rough appearance. This is contrary to the smooth endoplasmic reticulum which does not have these membrane bound ribosomes. This means that the rough endoplasmic reticulum is responsible for the production of polypeptides that are about to be taken through the membrane to be post-modified. ",

  "Ribosomes": "While examining the animal and plant cell through a microscope, you might have seen numerous organelles that work together to complete the cell activities. One of the essential cell organelles are ribosomes, which are in charge of protein synthesis. The ribosome is a complex made of protein and RNA and which adds up to numerous million Daltons in size and assumes an important part in the course of decoding the genetic message reserved in the genome into protein.",

  "Golgi apparatus": "Golgi apparatus, also called Golgi complex or Golgi body, membrane-bound organelle of eukaryotic cells (cells with clearly defined nuclei) that is made up of a series of flattened, stacked pouches called cisternae. The Golgi apparatus is responsible for transporting, modifying, and packaging proteins and lipids into vesicles for delivery to targeted destinations. It is located in the cytoplasm next to the endoplasmic reticulum and near the cell nucleus. While many types of cells contain only one or several Golgi apparatus, plant cells can contain hundreds.",

  "Secretion being released from cell by exocytosis": "Exocytosis is the cellular process in which intracellular vesicles in the cytoplasm fuse with the plasma membrane and release or 'secrete' their contents into the extracellular space. Exocytosis can be constitutive (occurring all the time) or regulated. Constitutive exocytosis is important in transporting proteins like receptors that function in the plasma membrane. Regulated exocytosis is triggered when a cell receives a signal from the outside.<br> Many of the products that cells secrete function specifically for the tissue type in which the cells reside or are transmitted to more distant parts of the body. Most of these products are proteins that have gone through rigorous quality control and modification processes in the endoplasmic reticulum and Golgi membranes. It is in the trans -Golgi network, the 'downstream' end of the Golgi apparatus, where cellular products are sorted and accumulate in exocytic vesicles.",

  "Peroxisome": "Peroxisomes are small, membrane-enclosed organelles that contain enzymes involved in a variety of metabolic reactions, including several aspects of energy metabolism. Although peroxisomes are morphologically similar to lysosomes, they are assembled, like mitochondria and chloroplasts, from proteins that are synthesized on free ribosomes and then imported into peroxisomes as completed polypeptide chains. Although peroxisomes do not contain their own genomes, they are similar to mitochondria and chloroplasts in that they replicate by division.",

  "Cytoskeletal elements": "The cytoskeleton is composed of protein polymers. Specialized cytoskeletal proteins (polymers of amino acids) connect to one another, forming long chains (polymers of proteins). These protein polymers support a cell’s structure from the inside, varying in length and position to create unique cell shapes as required for cellular function. The unique multifolded surfaces called microvilli in the cells of an animal’s small intestine are created by a specialized cytoskeleton. Microvilli extend the surface area lining the gut, increasing nutrient absorption rates. Other cytoskeletal proteins provide an internal network for rapid intracellular transport or promote cellular and organism movement by forming muscle fibers, flagella, or cilia. The proteins comprising the cytoskeleton can be divided into three classes: microfilaments, intermediate filaments, and microtubules.",

  "Microtubule": "Microtubules are polymers of tubulin that form part of the cytoskeleton and provide structure and shape to eukaryotic cells. Microtubules can grow as long as 50 micrometres and are highly dynamic. The outer diameter of a microtubule is between 23 and 27 nm while the inner diameter is between 11 and 15 nm.",

  "Intermediate filaments": "Intermediate filaments (IFs) are cytoskeletal structural components found in the cells of vertebrates, and many invertebrates. Homologues of the IF protein have been noted in an invertebrate, the cephalochordate Branchiostoma. Intermediate filaments are composed of a family of related proteins sharing common structural and sequence features. Initially designated 'intermediate' because their average diameter (10 nm) is between those of narrower microfilaments (actin) and wider myosin filaments found in muscle cells, the diameter of intermediate filaments is now commonly compared to actin microfilaments (7 nm) and microtubules (25 nm). Intermediate filaments are subcategorized into six types based on similarities in amino acid sequence and protein structure. Most types are cytoplasmic, but one type, Type V is a nuclear lamin. Unlike microtubules, IF distribution in cells show no good correlation with the distribution of either mitochondria or endoplasmic reticulum.",

  "Centrosome matrix": "Pericentriolar material. A network of small fibers that surrounds the centrioles in cells; contains the microtubule nucleating activity of the centrosome.",

  "Centrioles": "In cell biology a centriole is a cylindrical organelle composed mainly of a protein called tubulin. Centrioles are found in most eukaryotic cells. A bound pair of centrioles, surrounded by a shapeless mass of dense material, called the pericentriolar material, makes up a structure called a centrosome.",

  "Lysosome": "A lysosome is a membrane-bound cell organelle that contains digestive enzymes. Lysosomes are involved with various cell processes. They break down excess or worn-out cell parts. They may be used to destroy invading viruses and bacteria.",

  "Cytosol": "The cytosol, also known as intracellular fluid (ICF) or cytoplasmic matrix, or groundplasm,[2] is the liquid found inside cells. It is separated into compartments by membranes. For example, the mitochondrial matrix separates the mitochondrion into many compartments. In the eukaryotic cell, the cytosol is surrounded by the cell membrane and is part of the cytoplasm, which also comprises the mitochondria, plastids, and other organelles (but not their internal fluids and structures); the cell nucleus is separate. The cytosol is thus a liquid matrix around the organelles. In prokaryotes, most of the chemical reactions of metabolism take place in the cytosol, while a few take place in membranes or in the periplasmic space. In eukaryotes, while many metabolic pathways still occur in the cytosol, others take place within organelles.",

  "Mitochondrion": "The mitochondrion (plural mitochondria) is a membrane-bound organelle found in the cytoplasm of eukaryotic cells. It is the power house of the cell; it is responsible for cellular respiration and production of (most) ATP in the cell. Each cell can have from one to thousands of mitochondria. Mitochondria also contain extranuclear DNA that encodes a number of rRNAs, tRNAs, and proteins.",

  "Smooth endoplasmic reticulum": "The smooth endoplasmic reticulum (smooth ER) is a membranous organelle found in most eukaryotic cells. It is a subset of the endomembrane system of the endoplasmic reticulum. Its main functions are the synthesis of lipids, steroid hormones, the detoxification of harmful metabolic byproducts and the storage and metabolism of calcium ions within the cell. The smooth ER is distinguished from the other parts of the endoplasmic reticulum by the absence of membrane-bound ribosomes. This organelle is also morphologically distinct, often made of tubular structures called cisternae.",

  "Nucleolus": "The nucleolus is a region found within the cell nucleus that is concerned with producing and assembling the cell's ribosomes. Following assembly, ribosomes are transported to the cell cytoplasm where they serve as the sites for protein synthesis.",

  "Chromatin": "Chromatin is a mass of genetic material composed of DNA and proteins that condense to form chromosomes during eukaryotic cell division. Chromatin is located in the nucleus of our cells. <br> The primary function of chromatin is to compress the DNA into a compact unit that will be less voluminous and can fit within the nucleus. Chromatin consists of complexes of small proteins known as histones and DNA. <br> Histones help organize DNA into structures called nucleosomes by providing a base on which the DNA can be wrapped around. A nucleosome consists of a DNA sequence of about 150 base pairs that is wrapped around a set of eight histones called an octamer."
}
